import Head from "next/head";
import Logo from "./logo";
import Nav from "./nav"; 

export default function Header() {
  return (
    <>
      <Head>
        <title>Static Mania</title>
        <meta name="description" content="Generated by Rubiyet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <div className="h-[4.5rem] px-[5.1875rem] flex items-center justify-between select-none">
        <Logo /> {/* <Logo /> is a component that is imported from logo.jsx */}
        <Nav /> {/* <Nav /> is a component that is imported from nav.jsx */}
      </div>
    </>
  );
}
